name: install
on:
  push:
    branches:
      - master
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install kind
        uses: helm/kind-action@v1.4.0
        with:
          config: config.yaml
      - name: Test1
        run: |
          kubectl cluster-info
          kubectl get storageclass standard
      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.3'
      - name: Test2
        run: |
          sleep 60
          kubectl get nodes -o wide
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm upgrade -i nginx bitnami/nginx
          kubectl get pods -A -o wide
